pub mod cli;
pub mod completion;
pub mod config;
pub mod doctor;
pub mod domain;
pub mod error;
pub mod interactive;
pub mod orchestrator;
pub mod patch;
pub mod planner;
pub mod prompts;
pub mod providers;
pub mod runtime;
pub mod security;
pub mod service;
pub mod state;
pub mod tui;
pub mod workspace;

pub use error::{HarnessError, HarnessResult};
